name: Placeholder
description: |
  **placeholder
title: placeholder
labels: placeholder
assignees:
  -
body:
  - type: input
    id: id_test
    attributes:
      label: Placeholder
      description: description 
      placeholder: 
    validations:
      required: true
 
