name: Placeholder
description: |
  **placeholder
title: placeholder
labels: placeholder
assignees:
  -
body:
  - type: input
    id: id_test
    attributes:
      label: Placeholder
      description: description 
      placeholder: 
    validations:
      required: true
  - type: dropdown
    id: test_dropdown
    attributes:
      label: Dropdown test
      description: description
      options: 
      - Item 1
      - Item 2
      - Item 3
      - Item 4
      - Item 5
 
